package com.letu.healthplatform.platformmanage.user.vo;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class AppUserVo {
   
    private Integer userId;

   
    private String userName;

   
    private String userSex;

   
    private Date userBirthday;

  
    private Integer userHeight;

  
    private Integer userWeight;

   
    private String userNative;

   
    private Integer loginId;

    private String userTelephone;

  
    private String userAddress;

    
    private String userAddressInfo;

   
    private String userEducation;

    
    private String userRelationship;

    
    private String loginTelephone;
    
    /** 检测时间 */
    private Date tTestingTime;

    /** 检测项目 */
    private String tSiProject;
    
    /**来样编号**/
    private String tComeNumber;
    
    
    
    /**
	 * @return the tComeNumber
	 */
	public String gettComeNumber() {
		return tComeNumber;
	}


	/**
	 * @param tComeNumber the tComeNumber to set
	 */
	public void settComeNumber(String tComeNumber) {
		this.tComeNumber = tComeNumber;
	}


	/**
	 * @return the tTestingTime
	 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date gettTestingTime() {
		return tTestingTime;
	}


	/**
	 * @param tTestingTime the tTestingTime to set
	 */
	public void settTestingTime(Date tTestingTime) {
		this.tTestingTime = tTestingTime;
	}


	/**
	 * @return the tSiProject
	 */
	public String gettSiProject() {
		return tSiProject;
	}


	/**
	 * @param tSiProject the tSiProject to set
	 */
	public void settSiProject(String tSiProject) {
		this.tSiProject = tSiProject;
	}


	public Integer getUserId() {
        return userId;
    }

  
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_sex
     *
     * @return the value of t_user.user_sex
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_sex
     *
     * @param userSex the value for t_user.user_sex
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_birthday
     *
     * @return the value of t_user.user_birthday
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_birthday
     *
     * @param userBirthday the value for t_user.user_birthday
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_height
     *
     * @return the value of t_user.user_height
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Integer getUserHeight() {
        return userHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_height
     *
     * @param userHeight the value for t_user.user_height
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserHeight(Integer userHeight) {
        this.userHeight = userHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_weight
     *
     * @return the value of t_user.user_weight
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Integer getUserWeight() {
        return userWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_weight
     *
     * @param userWeight the value for t_user.user_weight
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserWeight(Integer userWeight) {
        this.userWeight = userWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_native
     *
     * @return the value of t_user.user_native
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserNative() {
        return userNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_native
     *
     * @param userNative the value for t_user.user_native
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserNative(String userNative) {
        this.userNative = userNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.login_id
     *
     * @return the value of t_user.login_id
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.login_id
     *
     * @param loginId the value for t_user.login_id
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_telephone
     *
     * @return the value of t_user.user_telephone
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_telephone
     *
     * @param userTelephone the value for t_user.user_telephone
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_address
     *
     * @return the value of t_user.user_address
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_address
     *
     * @param userAddress the value for t_user.user_address
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_address_info
     *
     * @return the value of t_user.user_address_info
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserAddressInfo() {
        return userAddressInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_address_info
     *
     * @param userAddressInfo the value for t_user.user_address_info
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserAddressInfo(String userAddressInfo) {
        this.userAddressInfo = userAddressInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_education
     *
     * @return the value of t_user.user_education
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserEducation() {
        return userEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_education
     *
     * @param userEducation the value for t_user.user_education
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserEducation(String userEducation) {
        this.userEducation = userEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_relationship
     *
     * @return the value of t_user.user_relationship
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getUserRelationship() {
        return userRelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_relationship
     *
     * @param userRelationship the value for t_user.user_relationship
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setUserRelationship(String userRelationship) {
        this.userRelationship = userRelationship;
    }

	public String getLoginTelephone() {
		return loginTelephone;
	}

	public void setLoginTelephone(String loginTelephone) {
		this.loginTelephone = loginTelephone;
	}
    
    
}