package com.letu.healthplatform.platformmanage.report.model;

public class ReportResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_result.report_id
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_result.gene_type
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    private String geneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_result.gene_code
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    private String geneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_result.report_value
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    private String reportValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_result.sample_number
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    private String sampleNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_result.report_id
     *
     * @return the value of t_report_result.report_id
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_result.report_id
     *
     * @param reportId the value for t_report_result.report_id
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_result.gene_type
     *
     * @return the value of t_report_result.gene_type
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public String getGeneType() {
        return geneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_result.gene_type
     *
     * @param geneType the value for t_report_result.gene_type
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public void setGeneType(String geneType) {
        this.geneType = geneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_result.gene_code
     *
     * @return the value of t_report_result.gene_code
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public String getGeneCode() {
        return geneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_result.gene_code
     *
     * @param geneCode the value for t_report_result.gene_code
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public void setGeneCode(String geneCode) {
        this.geneCode = geneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_result.report_value
     *
     * @return the value of t_report_result.report_value
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public String getReportValue() {
        return reportValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_result.report_value
     *
     * @param reportValue the value for t_report_result.report_value
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public void setReportValue(String reportValue) {
        this.reportValue = reportValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_result.sample_number
     *
     * @return the value of t_report_result.sample_number
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public String getSampleNumber() {
        return sampleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_result.sample_number
     *
     * @param sampleNumber the value for t_report_result.sample_number
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    public void setSampleNumber(String sampleNumber) {
        this.sampleNumber = sampleNumber;
    }
}