package com.letu.healthplatform.platformmanage.report.model;

import java.util.Date;

public class SaleMail implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_sale_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private Integer tSaleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_sale_name
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private String tSaleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_sale_sex
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private String tSaleSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_sale_telphone
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private String tSaleTelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_sale_email
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private String tSaleEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_batch_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private Integer tBatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_batch_topic
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private String tBatchTopic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_batch_type
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private Integer tBatchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_status
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private Integer tStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_send_time
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private Date tSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_cc_email
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private String tCcEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sale_mail.t_send_content
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    private String tSendContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_id
     *
     * @return the value of t_sale_mail.t_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_id
     *
     * @param tId the value for t_sale_mail.t_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_sale_id
     *
     * @return the value of t_sale_mail.t_sale_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public Integer gettSaleId() {
        return tSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_sale_id
     *
     * @param tSaleId the value for t_sale_mail.t_sale_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settSaleId(Integer tSaleId) {
        this.tSaleId = tSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_sale_name
     *
     * @return the value of t_sale_mail.t_sale_name
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public String gettSaleName() {
        return tSaleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_sale_name
     *
     * @param tSaleName the value for t_sale_mail.t_sale_name
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settSaleName(String tSaleName) {
        this.tSaleName = tSaleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_sale_sex
     *
     * @return the value of t_sale_mail.t_sale_sex
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public String gettSaleSex() {
        return tSaleSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_sale_sex
     *
     * @param tSaleSex the value for t_sale_mail.t_sale_sex
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settSaleSex(String tSaleSex) {
        this.tSaleSex = tSaleSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_sale_telphone
     *
     * @return the value of t_sale_mail.t_sale_telphone
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public String gettSaleTelphone() {
        return tSaleTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_sale_telphone
     *
     * @param tSaleTelphone the value for t_sale_mail.t_sale_telphone
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settSaleTelphone(String tSaleTelphone) {
        this.tSaleTelphone = tSaleTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_sale_email
     *
     * @return the value of t_sale_mail.t_sale_email
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public String gettSaleEmail() {
        return tSaleEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_sale_email
     *
     * @param tSaleEmail the value for t_sale_mail.t_sale_email
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settSaleEmail(String tSaleEmail) {
        this.tSaleEmail = tSaleEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_batch_id
     *
     * @return the value of t_sale_mail.t_batch_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public Integer gettBatchId() {
        return tBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_batch_id
     *
     * @param tBatchId the value for t_sale_mail.t_batch_id
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settBatchId(Integer tBatchId) {
        this.tBatchId = tBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_batch_topic
     *
     * @return the value of t_sale_mail.t_batch_topic
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public String gettBatchTopic() {
        return tBatchTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_batch_topic
     *
     * @param tBatchTopic the value for t_sale_mail.t_batch_topic
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settBatchTopic(String tBatchTopic) {
        this.tBatchTopic = tBatchTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_batch_type
     *
     * @return the value of t_sale_mail.t_batch_type
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public Integer gettBatchType() {
        return tBatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_batch_type
     *
     * @param tBatchType the value for t_sale_mail.t_batch_type
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settBatchType(Integer tBatchType) {
        this.tBatchType = tBatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_status
     *
     * @return the value of t_sale_mail.t_status
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_status
     *
     * @param tStatus the value for t_sale_mail.t_status
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_send_time
     *
     * @return the value of t_sale_mail.t_send_time
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public Date gettSendTime() {
        return tSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_send_time
     *
     * @param tSendTime the value for t_sale_mail.t_send_time
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settSendTime(Date tSendTime) {
        this.tSendTime = tSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_cc_email
     *
     * @return the value of t_sale_mail.t_cc_email
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public String gettCcEmail() {
        return tCcEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_cc_email
     *
     * @param tCcEmail the value for t_sale_mail.t_cc_email
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settCcEmail(String tCcEmail) {
        this.tCcEmail = tCcEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sale_mail.t_send_content
     *
     * @return the value of t_sale_mail.t_send_content
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public String gettSendContent() {
        return tSendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sale_mail.t_send_content
     *
     * @param tSendContent the value for t_sale_mail.t_send_content
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    public void settSendContent(String tSendContent) {
        this.tSendContent = tSendContent;
    }
}