package com.letu.healthplatform.platformmanage.report.model;

import java.util.Date;

public class SampleReport implements java.io.Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_batch_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Integer tBatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_batch_type
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Integer tBatchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_user_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Integer tUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_sale_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Integer tSaleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_report_status
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Integer tReportStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_report_time
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Date tReportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_logistics
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private String tLogistics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_logistics_number
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private String tLogisticsNumber;
    
    private String userName;
    
    private String tSampleBatch;
    
    private String saleUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_status
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Integer tStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample_report.t_createtime
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    private Date tCreatetime;

    /**多个患者ID**/
    private String  tUserIds;
    
    private String batchNumber;
    
    /**
	 * @return the tUserIds
	 */
	public String gettUserIds() {
		return tUserIds;
	}

	
	/**
	 * @param tUserIds the tUserIds to set
	 */
	public void settUserIds(String tUserIds) {
		this.tUserIds = tUserIds;
	}

	public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_id
     *
     * @param tId the value for t_sample_report.t_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_batch_id
     *
     * @return the value of t_sample_report.t_batch_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Integer gettBatchId() {
        return tBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_batch_id
     *
     * @param tBatchId the value for t_sample_report.t_batch_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settBatchId(Integer tBatchId) {
        this.tBatchId = tBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_batch_type
     *
     * @return the value of t_sample_report.t_batch_type
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Integer gettBatchType() {
        return tBatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_batch_type
     *
     * @param tBatchType the value for t_sample_report.t_batch_type
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settBatchType(Integer tBatchType) {
        this.tBatchType = tBatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_user_id
     *
     * @return the value of t_sample_report.t_user_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Integer gettUserId() {
        return tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_user_id
     *
     * @param tUserId the value for t_sample_report.t_user_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settUserId(Integer tUserId) {
        this.tUserId = tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_sale_id
     *
     * @return the value of t_sample_report.t_sale_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Integer gettSaleId() {
        return tSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_sale_id
     *
     * @param tSaleId the value for t_sample_report.t_sale_id
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settSaleId(Integer tSaleId) {
        this.tSaleId = tSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_report_status
     *
     * @return the value of t_sample_report.t_report_status
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Integer gettReportStatus() {
        return tReportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_report_status
     *
     * @param tReportStatus the value for t_sample_report.t_report_status
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settReportStatus(Integer tReportStatus) {
        this.tReportStatus = tReportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_report_time
     *
     * @return the value of t_sample_report.t_report_time
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Date gettReportTime() {
        return tReportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_report_time
     *
     * @param tReportTime the value for t_sample_report.t_report_time
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settReportTime(Date tReportTime) {
        this.tReportTime = tReportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_logistics
     *
     * @return the value of t_sample_report.t_logistics
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public String gettLogistics() {
        return tLogistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_logistics
     *
     * @param tLogistics the value for t_sample_report.t_logistics
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settLogistics(String tLogistics) {
        this.tLogistics = tLogistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_logistics_number
     *
     * @return the value of t_sample_report.t_logistics_number
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public String gettLogisticsNumber() {
        return tLogisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_logistics_number
     *
     * @param tLogisticsNumber the value for t_sample_report.t_logistics_number
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settLogisticsNumber(String tLogisticsNumber) {
        this.tLogisticsNumber = tLogisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_status
     *
     * @return the value of t_sample_report.t_status
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_status
     *
     * @param tStatus the value for t_sample_report.t_status
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample_report.t_createtime
     *
     * @return the value of t_sample_report.t_createtime
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public Date gettCreatetime() {
        return tCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample_report.t_createtime
     *
     * @param tCreatetime the value for t_sample_report.t_createtime
     *
     * @mbggenerated Mon Jan 22 16:48:11 CST 2018
     */
    public void settCreatetime(Date tCreatetime) {
        this.tCreatetime = tCreatetime;
    }


	public String getUserName() {
		return userName;
	}


	public void setUserName(String userName) {
		this.userName = userName;
	}


	public String gettSampleBatch() {
		return tSampleBatch;
	}


	public void settSampleBatch(String tSampleBatch) {
		this.tSampleBatch = tSampleBatch;
	}


	public String getSaleUserName() {
		return saleUserName;
	}


	public void setSaleUserName(String saleUserName) {
		this.saleUserName = saleUserName;
	}


	public String getBatchNumber() {
		return batchNumber;
	}


	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}
    
    
    
}