package com.letu.healthplatform.platformmanage.report.model;

import java.util.Date;

public class SortMessage implements java.io.Serializable {
    
    private Integer tId;

    
    private Integer tUserId;

    
    private String tUserName;

  
    private String tUserSex;

  
    private String tUserTelphone;

   
    private String tUserEmail;

   
    private String tLogistics;

   
    private String tLogisticsNumber;

  
    private Integer tBatchId;

   
    private String tBatchTopic;

 
    private Integer tBatchType;

   
    private Integer tStatus;

  
    private Date tSendTime;

   
    private String tSendContent;

   
    private Integer tSaleId;

  
    private Integer tSendEmailTatus;


    private Date tSendMailTime;
    
    
    private String saleUserName;
    
    
    private String saleEmail;
    
    
    private Integer tType;

  
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_id
     *
     * @param tId the value for t_sort_message.t_id
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_user_id
     *
     * @return the value of t_sort_message.t_user_id
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Integer gettUserId() {
        return tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_user_id
     *
     * @param tUserId the value for t_sort_message.t_user_id
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settUserId(Integer tUserId) {
        this.tUserId = tUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_user_name
     *
     * @return the value of t_sort_message.t_user_name
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettUserName() {
        return tUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_user_name
     *
     * @param tUserName the value for t_sort_message.t_user_name
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settUserName(String tUserName) {
        this.tUserName = tUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_user_sex
     *
     * @return the value of t_sort_message.t_user_sex
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettUserSex() {
        return tUserSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_user_sex
     *
     * @param tUserSex the value for t_sort_message.t_user_sex
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settUserSex(String tUserSex) {
        this.tUserSex = tUserSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_user_telphone
     *
     * @return the value of t_sort_message.t_user_telphone
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettUserTelphone() {
        return tUserTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_user_telphone
     *
     * @param tUserTelphone the value for t_sort_message.t_user_telphone
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settUserTelphone(String tUserTelphone) {
        this.tUserTelphone = tUserTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_user_email
     *
     * @return the value of t_sort_message.t_user_email
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettUserEmail() {
        return tUserEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_user_email
     *
     * @param tUserEmail the value for t_sort_message.t_user_email
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settUserEmail(String tUserEmail) {
        this.tUserEmail = tUserEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_logistics
     *
     * @return the value of t_sort_message.t_logistics
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettLogistics() {
        return tLogistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_logistics
     *
     * @param tLogistics the value for t_sort_message.t_logistics
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settLogistics(String tLogistics) {
        this.tLogistics = tLogistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_logistics_number
     *
     * @return the value of t_sort_message.t_logistics_number
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettLogisticsNumber() {
        return tLogisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_logistics_number
     *
     * @param tLogisticsNumber the value for t_sort_message.t_logistics_number
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settLogisticsNumber(String tLogisticsNumber) {
        this.tLogisticsNumber = tLogisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_batch_id
     *
     * @return the value of t_sort_message.t_batch_id
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Integer gettBatchId() {
        return tBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_batch_id
     *
     * @param tBatchId the value for t_sort_message.t_batch_id
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settBatchId(Integer tBatchId) {
        this.tBatchId = tBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_batch_topic
     *
     * @return the value of t_sort_message.t_batch_topic
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettBatchTopic() {
        return tBatchTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_batch_topic
     *
     * @param tBatchTopic the value for t_sort_message.t_batch_topic
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settBatchTopic(String tBatchTopic) {
        this.tBatchTopic = tBatchTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_batch_type
     *
     * @return the value of t_sort_message.t_batch_type
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Integer gettBatchType() {
        return tBatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_batch_type
     *
     * @param tBatchType the value for t_sort_message.t_batch_type
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settBatchType(Integer tBatchType) {
        this.tBatchType = tBatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_status
     *
     * @return the value of t_sort_message.t_status
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_status
     *
     * @param tStatus the value for t_sort_message.t_status
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_send_time
     *
     * @return the value of t_sort_message.t_send_time
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Date gettSendTime() {
        return tSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_send_time
     *
     * @param tSendTime the value for t_sort_message.t_send_time
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settSendTime(Date tSendTime) {
        this.tSendTime = tSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_send_content
     *
     * @return the value of t_sort_message.t_send_content
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public String gettSendContent() {
        return tSendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_send_content
     *
     * @param tSendContent the value for t_sort_message.t_send_content
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settSendContent(String tSendContent) {
        this.tSendContent = tSendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_sale_id
     *
     * @return the value of t_sort_message.t_sale_id
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Integer gettSaleId() {
        return tSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_sale_id
     *
     * @param tSaleId the value for t_sort_message.t_sale_id
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settSaleId(Integer tSaleId) {
        this.tSaleId = tSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_send_email_tatus
     *
     * @return the value of t_sort_message.t_send_email_tatus
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Integer gettSendEmailTatus() {
        return tSendEmailTatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_send_email_tatus
     *
     * @param tSendEmailTatus the value for t_sort_message.t_send_email_tatus
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settSendEmailTatus(Integer tSendEmailTatus) {
        this.tSendEmailTatus = tSendEmailTatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_message.t_send_mail_time
     *
     * @return the value of t_sort_message.t_send_mail_time
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public Date gettSendMailTime() {
        return tSendMailTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_message.t_send_mail_time
     *
     * @param tSendMailTime the value for t_sort_message.t_send_mail_time
     *
     * @mbggenerated Wed Jan 24 10:00:47 CST 2018
     */
    public void settSendMailTime(Date tSendMailTime) {
        this.tSendMailTime = tSendMailTime;
    }

	public String getSaleUserName() {
		return saleUserName;
	}

	public void setSaleUserName(String saleUserName) {
		this.saleUserName = saleUserName;
	}

	public String getSaleEmail() {
		return saleEmail;
	}

	public void setSaleEmail(String saleEmail) {
		this.saleEmail = saleEmail;
	}

	public Integer gettType() {
		return tType;
	}

	public void settType(Integer tType) {
		this.tType = tType;
	}



    
    
}