package com.letu.healthplatform.platformmanage.home.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.home.model.Information;

public interface InformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insert(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insertSelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    Information selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKeySelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKey(Information record);
    /***
     * 分页查询
     * @param record
     * @return
     */
    List<Information>  selectByParam(Information record);
}