package com.letu.healthplatform.platformmanage.home.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.home.model.InformationType;

public interface InformationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information_type
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information_type
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insert(InformationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information_type
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insertSelective(InformationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information_type
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    InformationType selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information_type
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKeySelective(InformationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_information_type
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKey(InformationType record);
    
    /***
     * 分页查询
     * @param record
     * @return
     */
    List<InformationType>  selectByParam(InformationType record);
}