package com.letu.healthplatform.platformmanage.home.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.home.model.ProductBanner;
import com.letu.healthplatform.platformmanage.home.model.ProductPackage;

public interface ProductBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_banner
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int deleteByPrimaryKey(Integer tBannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_banner
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insert(ProductBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_banner
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insertSelective(ProductBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_banner
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    ProductBanner selectByPrimaryKey(Integer tBannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_banner
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKeySelective(ProductBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_banner
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKey(ProductBanner record);
    
    
    
    List<ProductBanner>  selectByParam(ProductBanner record);
}