package com.letu.healthplatform.platformmanage.home.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.home.model.ProductPackage;

public interface ProductPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_package
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int deleteByPrimaryKey(Integer tPackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_package
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insert(ProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_package
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int insertSelective(ProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_package
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    ProductPackage selectByPrimaryKey(Integer tPackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_package
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKeySelective(ProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_package
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    int updateByPrimaryKey(ProductPackage record);
    
    
    List<ProductPackage>  selectByParam(ProductPackage record);
    

}