package com.letu.healthplatform.platformmanage.home.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.home.model.Video;
import com.letu.healthplatform.platformmanage.home.model.VideoType;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    Video selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    int updateByPrimaryKey(Video record);
    
    /***
     * 查询
     * @param video
     * @return
     */
    List<Video> selectByParam(Video video);
}