package com.letu.healthplatform.platformmanage.home.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.home.model.VideoType;

public interface VideoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    int insert(VideoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    int insertSelective(VideoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    VideoType selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    int updateByPrimaryKeySelective(VideoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_m_video_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    int updateByPrimaryKey(VideoType record);
    /***
     * 查询
     * @param video
     * @return
     */
    List<VideoType> selectByParam(VideoType videoType);
}