package com.letu.healthplatform.platformmanage.user.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.user.model.AppLogin;

public interface AppLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int insert(AppLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int insertSelective(AppLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    AppLogin selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int updateByPrimaryKeySelective(AppLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int updateByPrimaryKey(AppLogin record);
    
    /***
     * 编辑
     * @param login
     * @return
     */
     List<AppLogin>  selectByParam(AppLogin  login);
}