package com.letu.healthplatform.platformmanage.user.mapper;

import com.letu.healthplatform.platformmanage.user.model.AppUserType;

public interface AppUserTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int deleteByPrimaryKey(Integer usertypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int insert(AppUserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int insertSelective(AppUserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    AppUserType selectByPrimaryKey(Integer usertypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int updateByPrimaryKeySelective(AppUserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_type
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    int updateByPrimaryKey(AppUserType record);
}