package com.letu.healthplatform.platformmanage.sys.model;
/***
 * 地区
 * @author chenfei
 *
 */
public class Province {
    
    private Integer provinceId;

   
    private String provinceName;

   
    private Integer provincePid;

  
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.province_id
     *
     * @param provinceId the value for t_province.province_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.province_name
     *
     * @return the value of t_province.province_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.province_name
     *
     * @param provinceName the value for t_province.province_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_province.province_pid
     *
     * @return the value of t_province.province_pid
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getProvincePid() {
        return provincePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_province.province_pid
     *
     * @param provincePid the value for t_province.province_pid
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setProvincePid(Integer provincePid) {
        this.provincePid = provincePid;
    }
}