package com.letu.healthplatform.platformmanage.sys.model;

public class UserType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_type.usertype_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer usertypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_type.usertype_relationship
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String usertypeRelationship;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_type.usertype_id
     *
     * @return the value of t_user_type.usertype_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUsertypeId() {
        return usertypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_type.usertype_id
     *
     * @param usertypeId the value for t_user_type.usertype_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUsertypeId(Integer usertypeId) {
        this.usertypeId = usertypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_type.usertype_relationship
     *
     * @return the value of t_user_type.usertype_relationship
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUsertypeRelationship() {
        return usertypeRelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_type.usertype_relationship
     *
     * @param usertypeRelationship the value for t_user_type.usertype_relationship
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUsertypeRelationship(String usertypeRelationship) {
        this.usertypeRelationship = usertypeRelationship;
    }
}