package com.letu.healthplatform.platformmanage.sys.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userinfo_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_drink
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoDrink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_experience
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_eat
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoEat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_sleep
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoSleep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_smoking
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoSmoking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_drugallergy
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userinfoDrugallergy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_medicalhistory
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userinfoMedicalhistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_familyhistory
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userinfoFamilyhistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_smokenum
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoSmokenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.otherdisease
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String otherdisease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.sample
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String sample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.testitem
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String testitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.personal_case_history
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String personalCaseHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.personal_case_history2
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String personalCaseHistory2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.personal_case_history3
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String personalCaseHistory3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.personal_case_history4
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String personalCaseHistory4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_smoketime
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoSmoketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_quitsmoking
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoQuitsmoking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_diploma
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoDiploma;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_empty_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoEmptyLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_empty_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoEmptyRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_corrected_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoCorrectedLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_corrected_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoCorrectedRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_ball_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoBallLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_ball_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoBallRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_astigmatism_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoAstigmatismLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_astigmatism_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoAstigmatismRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_axial_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoAxialLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_axial_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Float userinfoAxialRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_myopiatime
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoMyopiatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_eye_diseases
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoEyeDiseases;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_eye_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userinfoEyeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_intermarriage
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoIntermarriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_genetic
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoGenetic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_genetic_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userinfoGeneticName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userInfo_father
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userinfoFather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.mother
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer mother;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userinfo_id
     *
     * @return the value of t_user_info.userinfo_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoId() {
        return userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userinfo_id
     *
     * @param userinfoId the value for t_user_info.userinfo_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoId(Integer userinfoId) {
        this.userinfoId = userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_drink
     *
     * @return the value of t_user_info.userInfo_drink
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoDrink() {
        return userinfoDrink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_drink
     *
     * @param userinfoDrink the value for t_user_info.userInfo_drink
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoDrink(Integer userinfoDrink) {
        this.userinfoDrink = userinfoDrink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_experience
     *
     * @return the value of t_user_info.userInfo_experience
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoExperience() {
        return userinfoExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_experience
     *
     * @param userinfoExperience the value for t_user_info.userInfo_experience
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoExperience(Integer userinfoExperience) {
        this.userinfoExperience = userinfoExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_eat
     *
     * @return the value of t_user_info.userInfo_eat
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoEat() {
        return userinfoEat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_eat
     *
     * @param userinfoEat the value for t_user_info.userInfo_eat
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoEat(Integer userinfoEat) {
        this.userinfoEat = userinfoEat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_sleep
     *
     * @return the value of t_user_info.userInfo_sleep
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoSleep() {
        return userinfoSleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_sleep
     *
     * @param userinfoSleep the value for t_user_info.userInfo_sleep
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoSleep(Integer userinfoSleep) {
        this.userinfoSleep = userinfoSleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_smoking
     *
     * @return the value of t_user_info.userInfo_smoking
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoSmoking() {
        return userinfoSmoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_smoking
     *
     * @param userinfoSmoking the value for t_user_info.userInfo_smoking
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoSmoking(Integer userinfoSmoking) {
        this.userinfoSmoking = userinfoSmoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_drugallergy
     *
     * @return the value of t_user_info.userInfo_drugallergy
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserinfoDrugallergy() {
        return userinfoDrugallergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_drugallergy
     *
     * @param userinfoDrugallergy the value for t_user_info.userInfo_drugallergy
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoDrugallergy(String userinfoDrugallergy) {
        this.userinfoDrugallergy = userinfoDrugallergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_medicalhistory
     *
     * @return the value of t_user_info.userInfo_medicalhistory
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserinfoMedicalhistory() {
        return userinfoMedicalhistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_medicalhistory
     *
     * @param userinfoMedicalhistory the value for t_user_info.userInfo_medicalhistory
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoMedicalhistory(String userinfoMedicalhistory) {
        this.userinfoMedicalhistory = userinfoMedicalhistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_familyhistory
     *
     * @return the value of t_user_info.userInfo_familyhistory
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserinfoFamilyhistory() {
        return userinfoFamilyhistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_familyhistory
     *
     * @param userinfoFamilyhistory the value for t_user_info.userInfo_familyhistory
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoFamilyhistory(String userinfoFamilyhistory) {
        this.userinfoFamilyhistory = userinfoFamilyhistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_smokenum
     *
     * @return the value of t_user_info.userInfo_smokenum
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoSmokenum() {
        return userinfoSmokenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_smokenum
     *
     * @param userinfoSmokenum the value for t_user_info.userInfo_smokenum
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoSmokenum(Integer userinfoSmokenum) {
        this.userinfoSmokenum = userinfoSmokenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.otherdisease
     *
     * @return the value of t_user_info.otherdisease
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getOtherdisease() {
        return otherdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.otherdisease
     *
     * @param otherdisease the value for t_user_info.otherdisease
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setOtherdisease(String otherdisease) {
        this.otherdisease = otherdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.sample
     *
     * @return the value of t_user_info.sample
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.sample
     *
     * @param sample the value for t_user_info.sample
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setSample(String sample) {
        this.sample = sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.testitem
     *
     * @return the value of t_user_info.testitem
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getTestitem() {
        return testitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.testitem
     *
     * @param testitem the value for t_user_info.testitem
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setTestitem(String testitem) {
        this.testitem = testitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.personal_case_history
     *
     * @return the value of t_user_info.personal_case_history
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getPersonalCaseHistory() {
        return personalCaseHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.personal_case_history
     *
     * @param personalCaseHistory the value for t_user_info.personal_case_history
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setPersonalCaseHistory(String personalCaseHistory) {
        this.personalCaseHistory = personalCaseHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.personal_case_history2
     *
     * @return the value of t_user_info.personal_case_history2
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getPersonalCaseHistory2() {
        return personalCaseHistory2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.personal_case_history2
     *
     * @param personalCaseHistory2 the value for t_user_info.personal_case_history2
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setPersonalCaseHistory2(String personalCaseHistory2) {
        this.personalCaseHistory2 = personalCaseHistory2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.personal_case_history3
     *
     * @return the value of t_user_info.personal_case_history3
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getPersonalCaseHistory3() {
        return personalCaseHistory3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.personal_case_history3
     *
     * @param personalCaseHistory3 the value for t_user_info.personal_case_history3
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setPersonalCaseHistory3(String personalCaseHistory3) {
        this.personalCaseHistory3 = personalCaseHistory3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.personal_case_history4
     *
     * @return the value of t_user_info.personal_case_history4
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getPersonalCaseHistory4() {
        return personalCaseHistory4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.personal_case_history4
     *
     * @param personalCaseHistory4 the value for t_user_info.personal_case_history4
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setPersonalCaseHistory4(String personalCaseHistory4) {
        this.personalCaseHistory4 = personalCaseHistory4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_smoketime
     *
     * @return the value of t_user_info.userInfo_smoketime
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoSmoketime() {
        return userinfoSmoketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_smoketime
     *
     * @param userinfoSmoketime the value for t_user_info.userInfo_smoketime
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoSmoketime(Integer userinfoSmoketime) {
        this.userinfoSmoketime = userinfoSmoketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_quitsmoking
     *
     * @return the value of t_user_info.userInfo_quitsmoking
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoQuitsmoking() {
        return userinfoQuitsmoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_quitsmoking
     *
     * @param userinfoQuitsmoking the value for t_user_info.userInfo_quitsmoking
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoQuitsmoking(Integer userinfoQuitsmoking) {
        this.userinfoQuitsmoking = userinfoQuitsmoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_diploma
     *
     * @return the value of t_user_info.userInfo_diploma
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoDiploma() {
        return userinfoDiploma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_diploma
     *
     * @param userinfoDiploma the value for t_user_info.userInfo_diploma
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoDiploma(Integer userinfoDiploma) {
        this.userinfoDiploma = userinfoDiploma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_empty_left
     *
     * @return the value of t_user_info.userInfo_empty_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoEmptyLeft() {
        return userinfoEmptyLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_empty_left
     *
     * @param userinfoEmptyLeft the value for t_user_info.userInfo_empty_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoEmptyLeft(Float userinfoEmptyLeft) {
        this.userinfoEmptyLeft = userinfoEmptyLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_empty_right
     *
     * @return the value of t_user_info.userInfo_empty_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoEmptyRight() {
        return userinfoEmptyRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_empty_right
     *
     * @param userinfoEmptyRight the value for t_user_info.userInfo_empty_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoEmptyRight(Float userinfoEmptyRight) {
        this.userinfoEmptyRight = userinfoEmptyRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_corrected_left
     *
     * @return the value of t_user_info.userInfo_corrected_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoCorrectedLeft() {
        return userinfoCorrectedLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_corrected_left
     *
     * @param userinfoCorrectedLeft the value for t_user_info.userInfo_corrected_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoCorrectedLeft(Float userinfoCorrectedLeft) {
        this.userinfoCorrectedLeft = userinfoCorrectedLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_corrected_right
     *
     * @return the value of t_user_info.userInfo_corrected_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoCorrectedRight() {
        return userinfoCorrectedRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_corrected_right
     *
     * @param userinfoCorrectedRight the value for t_user_info.userInfo_corrected_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoCorrectedRight(Float userinfoCorrectedRight) {
        this.userinfoCorrectedRight = userinfoCorrectedRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_ball_left
     *
     * @return the value of t_user_info.userInfo_ball_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoBallLeft() {
        return userinfoBallLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_ball_left
     *
     * @param userinfoBallLeft the value for t_user_info.userInfo_ball_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoBallLeft(Float userinfoBallLeft) {
        this.userinfoBallLeft = userinfoBallLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_ball_right
     *
     * @return the value of t_user_info.userInfo_ball_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoBallRight() {
        return userinfoBallRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_ball_right
     *
     * @param userinfoBallRight the value for t_user_info.userInfo_ball_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoBallRight(Float userinfoBallRight) {
        this.userinfoBallRight = userinfoBallRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_astigmatism_left
     *
     * @return the value of t_user_info.userInfo_astigmatism_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoAstigmatismLeft() {
        return userinfoAstigmatismLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_astigmatism_left
     *
     * @param userinfoAstigmatismLeft the value for t_user_info.userInfo_astigmatism_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoAstigmatismLeft(Float userinfoAstigmatismLeft) {
        this.userinfoAstigmatismLeft = userinfoAstigmatismLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_astigmatism_right
     *
     * @return the value of t_user_info.userInfo_astigmatism_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoAstigmatismRight() {
        return userinfoAstigmatismRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_astigmatism_right
     *
     * @param userinfoAstigmatismRight the value for t_user_info.userInfo_astigmatism_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoAstigmatismRight(Float userinfoAstigmatismRight) {
        this.userinfoAstigmatismRight = userinfoAstigmatismRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_axial_left
     *
     * @return the value of t_user_info.userInfo_axial_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoAxialLeft() {
        return userinfoAxialLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_axial_left
     *
     * @param userinfoAxialLeft the value for t_user_info.userInfo_axial_left
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoAxialLeft(Float userinfoAxialLeft) {
        this.userinfoAxialLeft = userinfoAxialLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_axial_right
     *
     * @return the value of t_user_info.userInfo_axial_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Float getUserinfoAxialRight() {
        return userinfoAxialRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_axial_right
     *
     * @param userinfoAxialRight the value for t_user_info.userInfo_axial_right
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoAxialRight(Float userinfoAxialRight) {
        this.userinfoAxialRight = userinfoAxialRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_myopiatime
     *
     * @return the value of t_user_info.userInfo_myopiatime
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoMyopiatime() {
        return userinfoMyopiatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_myopiatime
     *
     * @param userinfoMyopiatime the value for t_user_info.userInfo_myopiatime
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoMyopiatime(Integer userinfoMyopiatime) {
        this.userinfoMyopiatime = userinfoMyopiatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_eye_diseases
     *
     * @return the value of t_user_info.userInfo_eye_diseases
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoEyeDiseases() {
        return userinfoEyeDiseases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_eye_diseases
     *
     * @param userinfoEyeDiseases the value for t_user_info.userInfo_eye_diseases
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoEyeDiseases(Integer userinfoEyeDiseases) {
        this.userinfoEyeDiseases = userinfoEyeDiseases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_eye_name
     *
     * @return the value of t_user_info.userInfo_eye_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserinfoEyeName() {
        return userinfoEyeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_eye_name
     *
     * @param userinfoEyeName the value for t_user_info.userInfo_eye_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoEyeName(String userinfoEyeName) {
        this.userinfoEyeName = userinfoEyeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_intermarriage
     *
     * @return the value of t_user_info.userInfo_intermarriage
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoIntermarriage() {
        return userinfoIntermarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_intermarriage
     *
     * @param userinfoIntermarriage the value for t_user_info.userInfo_intermarriage
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoIntermarriage(Integer userinfoIntermarriage) {
        this.userinfoIntermarriage = userinfoIntermarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_genetic
     *
     * @return the value of t_user_info.userInfo_genetic
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoGenetic() {
        return userinfoGenetic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_genetic
     *
     * @param userinfoGenetic the value for t_user_info.userInfo_genetic
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoGenetic(Integer userinfoGenetic) {
        this.userinfoGenetic = userinfoGenetic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_genetic_name
     *
     * @return the value of t_user_info.userInfo_genetic_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserinfoGeneticName() {
        return userinfoGeneticName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_genetic_name
     *
     * @param userinfoGeneticName the value for t_user_info.userInfo_genetic_name
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoGeneticName(String userinfoGeneticName) {
        this.userinfoGeneticName = userinfoGeneticName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userInfo_father
     *
     * @return the value of t_user_info.userInfo_father
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserinfoFather() {
        return userinfoFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userInfo_father
     *
     * @param userinfoFather the value for t_user_info.userInfo_father
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserinfoFather(Integer userinfoFather) {
        this.userinfoFather = userinfoFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.mother
     *
     * @return the value of t_user_info.mother
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getMother() {
        return mother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.mother
     *
     * @param mother the value for t_user_info.mother
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setMother(Integer mother) {
        this.mother = mother;
    }
}