package com.letu.healthplatform.platformmanage.sys.model;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_nmae
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userNmae;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_sex
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_birthday
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_height
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_weight
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer userWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_native
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userNative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.login_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_telephone
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_address
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_address_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userAddressInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_education
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_relationship
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    private String userRelationship;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_nmae
     *
     * @return the value of t_user.user_nmae
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserNmae() {
        return userNmae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_nmae
     *
     * @param userNmae the value for t_user.user_nmae
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserNmae(String userNmae) {
        this.userNmae = userNmae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_sex
     *
     * @return the value of t_user.user_sex
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_sex
     *
     * @param userSex the value for t_user.user_sex
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_birthday
     *
     * @return the value of t_user.user_birthday
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_birthday
     *
     * @param userBirthday the value for t_user.user_birthday
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_height
     *
     * @return the value of t_user.user_height
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserHeight() {
        return userHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_height
     *
     * @param userHeight the value for t_user.user_height
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserHeight(Integer userHeight) {
        this.userHeight = userHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_weight
     *
     * @return the value of t_user.user_weight
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getUserWeight() {
        return userWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_weight
     *
     * @param userWeight the value for t_user.user_weight
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserWeight(Integer userWeight) {
        this.userWeight = userWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_native
     *
     * @return the value of t_user.user_native
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserNative() {
        return userNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_native
     *
     * @param userNative the value for t_user.user_native
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserNative(String userNative) {
        this.userNative = userNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.login_id
     *
     * @return the value of t_user.login_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.login_id
     *
     * @param loginId the value for t_user.login_id
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_telephone
     *
     * @return the value of t_user.user_telephone
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_telephone
     *
     * @param userTelephone the value for t_user.user_telephone
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_address
     *
     * @return the value of t_user.user_address
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_address
     *
     * @param userAddress the value for t_user.user_address
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_address_info
     *
     * @return the value of t_user.user_address_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserAddressInfo() {
        return userAddressInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_address_info
     *
     * @param userAddressInfo the value for t_user.user_address_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserAddressInfo(String userAddressInfo) {
        this.userAddressInfo = userAddressInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_education
     *
     * @return the value of t_user.user_education
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserEducation() {
        return userEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_education
     *
     * @param userEducation the value for t_user.user_education
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserEducation(String userEducation) {
        this.userEducation = userEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_relationship
     *
     * @return the value of t_user.user_relationship
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public String getUserRelationship() {
        return userRelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_relationship
     *
     * @param userRelationship the value for t_user.user_relationship
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    public void setUserRelationship(String userRelationship) {
        this.userRelationship = userRelationship;
    }
}