package com.letu.healthplatform.platformmanage.home.model;

public class InformationType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information_type.t_id
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information_type.t_type
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    private String tType;
    
    private Integer tStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information_type.t_type_info
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    private String tTypeInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information_type.t_id
     *
     * @return the value of t_m_information_type.t_id
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information_type.t_id
     *
     * @param tId the value for t_m_information_type.t_id
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information_type.t_type
     *
     * @return the value of t_m_information_type.t_type
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    public String gettType() {
        return tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information_type.t_type
     *
     * @param tType the value for t_m_information_type.t_type
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    public void settType(String tType) {
        this.tType = tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information_type.t_type_info
     *
     * @return the value of t_m_information_type.t_type_info
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    public String gettTypeInfo() {
        return tTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information_type.t_type_info
     *
     * @param tTypeInfo the value for t_m_information_type.t_type_info
     *
     * @mbggenerated Tue Dec 19 14:55:00 CST 2017
     */
    public void settTypeInfo(String tTypeInfo) {
        this.tTypeInfo = tTypeInfo;
    }

	public Integer gettStatus() {
		return tStatus;
	}

	public void settStatus(Integer tStatus) {
		this.tStatus = tStatus;
	}
    
    
}