package com.letu.healthplatform.platformmanage.home.model;

import java.util.Date;

public class Information {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_id
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_title
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_stitle
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tStitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_author
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_source
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_tags
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_content
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_home_pic
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tHomePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_click
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Integer tClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_audit
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Integer tAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_top
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Integer tTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_comm
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Integer tComm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_remark
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_status
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Integer tStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_create_time
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Date tCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_create_by
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_modify_time
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Date tModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_modify_by
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private String tModifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_information.t_type_id
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    private Integer tTypeId;
    
    private String tType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_id
     *
     * @return the value of t_m_information.t_id
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_id
     *
     * @param tId the value for t_m_information.t_id
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_title
     *
     * @return the value of t_m_information.t_title
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettTitle() {
        return tTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_title
     *
     * @param tTitle the value for t_m_information.t_title
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settTitle(String tTitle) {
        this.tTitle = tTitle;
    }

    public String gettType() {
		return tType;
	}

	public void settType(String tType) {
		this.tType = tType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_stitle
     *
     * @return the value of t_m_information.t_stitle
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettStitle() {
        return tStitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_stitle
     *
     * @param tStitle the value for t_m_information.t_stitle
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settStitle(String tStitle) {
        this.tStitle = tStitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_author
     *
     * @return the value of t_m_information.t_author
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettAuthor() {
        return tAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_author
     *
     * @param tAuthor the value for t_m_information.t_author
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settAuthor(String tAuthor) {
        this.tAuthor = tAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_source
     *
     * @return the value of t_m_information.t_source
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettSource() {
        return tSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_source
     *
     * @param tSource the value for t_m_information.t_source
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settSource(String tSource) {
        this.tSource = tSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_tags
     *
     * @return the value of t_m_information.t_tags
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettTags() {
        return tTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_tags
     *
     * @param tTags the value for t_m_information.t_tags
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settTags(String tTags) {
        this.tTags = tTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_content
     *
     * @return the value of t_m_information.t_content
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettContent() {
        return tContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_content
     *
     * @param tContent the value for t_m_information.t_content
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settContent(String tContent) {
        this.tContent = tContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_home_pic
     *
     * @return the value of t_m_information.t_home_pic
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettHomePic() {
        return tHomePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_home_pic
     *
     * @param tHomePic the value for t_m_information.t_home_pic
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settHomePic(String tHomePic) {
        this.tHomePic = tHomePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_click
     *
     * @return the value of t_m_information.t_click
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Integer gettClick() {
        return tClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_click
     *
     * @param tClick the value for t_m_information.t_click
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settClick(Integer tClick) {
        this.tClick = tClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_audit
     *
     * @return the value of t_m_information.t_audit
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Integer gettAudit() {
        return tAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_audit
     *
     * @param tAudit the value for t_m_information.t_audit
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settAudit(Integer tAudit) {
        this.tAudit = tAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_top
     *
     * @return the value of t_m_information.t_top
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Integer gettTop() {
        return tTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_top
     *
     * @param tTop the value for t_m_information.t_top
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settTop(Integer tTop) {
        this.tTop = tTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_comm
     *
     * @return the value of t_m_information.t_comm
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Integer gettComm() {
        return tComm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_comm
     *
     * @param tComm the value for t_m_information.t_comm
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settComm(Integer tComm) {
        this.tComm = tComm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_remark
     *
     * @return the value of t_m_information.t_remark
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettRemark() {
        return tRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_remark
     *
     * @param tRemark the value for t_m_information.t_remark
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settRemark(String tRemark) {
        this.tRemark = tRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_status
     *
     * @return the value of t_m_information.t_status
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_status
     *
     * @param tStatus the value for t_m_information.t_status
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_create_time
     *
     * @return the value of t_m_information.t_create_time
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Date gettCreateTime() {
        return tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_create_time
     *
     * @param tCreateTime the value for t_m_information.t_create_time
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settCreateTime(Date tCreateTime) {
        this.tCreateTime = tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_create_by
     *
     * @return the value of t_m_information.t_create_by
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettCreateBy() {
        return tCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_create_by
     *
     * @param tCreateBy the value for t_m_information.t_create_by
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settCreateBy(String tCreateBy) {
        this.tCreateBy = tCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_modify_time
     *
     * @return the value of t_m_information.t_modify_time
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Date gettModifyTime() {
        return tModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_modify_time
     *
     * @param tModifyTime the value for t_m_information.t_modify_time
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settModifyTime(Date tModifyTime) {
        this.tModifyTime = tModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_modify_by
     *
     * @return the value of t_m_information.t_modify_by
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public String gettModifyBy() {
        return tModifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_modify_by
     *
     * @param tModifyBy the value for t_m_information.t_modify_by
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settModifyBy(String tModifyBy) {
        this.tModifyBy = tModifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_information.t_type_id
     *
     * @return the value of t_m_information.t_type_id
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public Integer gettTypeId() {
        return tTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_information.t_type_id
     *
     * @param tTypeId the value for t_m_information.t_type_id
     *
     * @mbggenerated Tue Dec 19 14:56:29 CST 2017
     */
    public void settTypeId(Integer tTypeId) {
        this.tTypeId = tTypeId;
    }
}