package com.letu.healthplatform.platformmanage.home.model;

import java.util.Date;

public class ProductPackage implements java.io.Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_package.t_package_id
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Integer tPackageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_package.t_package_url
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private String tPackageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_package.t_package_info
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private String tPackageInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_package.t_package_sort
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Integer tPackageSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_package.t_create_time
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Date tCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_package.t_status
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Integer tStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_package.t_package_id
     *
     * @return the value of t_m_package.t_package_id
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Integer gettPackageId() {
        return tPackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_package.t_package_id
     *
     * @param tPackageId the value for t_m_package.t_package_id
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settPackageId(Integer tPackageId) {
        this.tPackageId = tPackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_package.t_package_url
     *
     * @return the value of t_m_package.t_package_url
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public String gettPackageUrl() {
        return tPackageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_package.t_package_url
     *
     * @param tPackageUrl the value for t_m_package.t_package_url
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settPackageUrl(String tPackageUrl) {
        this.tPackageUrl = tPackageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_package.t_package_info
     *
     * @return the value of t_m_package.t_package_info
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public String gettPackageInfo() {
        return tPackageInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_package.t_package_info
     *
     * @param tPackageInfo the value for t_m_package.t_package_info
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settPackageInfo(String tPackageInfo) {
        this.tPackageInfo = tPackageInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_package.t_package_sort
     *
     * @return the value of t_m_package.t_package_sort
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Integer gettPackageSort() {
        return tPackageSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_package.t_package_sort
     *
     * @param tPackageSort the value for t_m_package.t_package_sort
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settPackageSort(Integer tPackageSort) {
        this.tPackageSort = tPackageSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_package.t_create_time
     *
     * @return the value of t_m_package.t_create_time
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Date gettCreateTime() {
        return tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_package.t_create_time
     *
     * @param tCreateTime the value for t_m_package.t_create_time
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settCreateTime(Date tCreateTime) {
        this.tCreateTime = tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_package.t_status
     *
     * @return the value of t_m_package.t_status
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_package.t_status
     *
     * @param tStatus the value for t_m_package.t_status
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }
}