package com.letu.healthplatform.platformmanage.home.model;

import java.util.Date;

public class ProductBanner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_banner.t_banner_id
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Integer tBannerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_banner.t_banner_url
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private String tBannerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_banner.t_banner_info
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private String tBannerInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_banner.t_banner_sort
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Integer tBannerSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_banner.t_create_time
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Date tCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_banner.t_status
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    private Integer tStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_banner.t_banner_id
     *
     * @return the value of t_m_banner.t_banner_id
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Integer gettBannerId() {
        return tBannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_banner.t_banner_id
     *
     * @param tBannerId the value for t_m_banner.t_banner_id
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settBannerId(Integer tBannerId) {
        this.tBannerId = tBannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_banner.t_banner_url
     *
     * @return the value of t_m_banner.t_banner_url
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public String gettBannerUrl() {
        return tBannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_banner.t_banner_url
     *
     * @param tBannerUrl the value for t_m_banner.t_banner_url
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settBannerUrl(String tBannerUrl) {
        this.tBannerUrl = tBannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_banner.t_banner_info
     *
     * @return the value of t_m_banner.t_banner_info
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public String gettBannerInfo() {
        return tBannerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_banner.t_banner_info
     *
     * @param tBannerInfo the value for t_m_banner.t_banner_info
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settBannerInfo(String tBannerInfo) {
        this.tBannerInfo = tBannerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_banner.t_banner_sort
     *
     * @return the value of t_m_banner.t_banner_sort
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Integer gettBannerSort() {
        return tBannerSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_banner.t_banner_sort
     *
     * @param tBannerSort the value for t_m_banner.t_banner_sort
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settBannerSort(Integer tBannerSort) {
        this.tBannerSort = tBannerSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_banner.t_create_time
     *
     * @return the value of t_m_banner.t_create_time
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Date gettCreateTime() {
        return tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_banner.t_create_time
     *
     * @param tCreateTime the value for t_m_banner.t_create_time
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settCreateTime(Date tCreateTime) {
        this.tCreateTime = tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_banner.t_status
     *
     * @return the value of t_m_banner.t_status
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_banner.t_status
     *
     * @param tStatus the value for t_m_banner.t_status
     *
     * @mbggenerated Mon Dec 18 15:10:39 CST 2017
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }
}