package com.letu.healthplatform.platformmanage.home.model;

public class VideoType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video_type.t_id
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video_type.t_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    private String tType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video_type.t_type_info
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    private String tTypeInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video_type.t_id
     *
     * @return the value of t_m_video_type.t_id
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video_type.t_id
     *
     * @param tId the value for t_m_video_type.t_id
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video_type.t_type
     *
     * @return the value of t_m_video_type.t_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    public String gettType() {
        return tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video_type.t_type
     *
     * @param tType the value for t_m_video_type.t_type
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    public void settType(String tType) {
        this.tType = tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video_type.t_type_info
     *
     * @return the value of t_m_video_type.t_type_info
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    public String gettTypeInfo() {
        return tTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video_type.t_type_info
     *
     * @param tTypeInfo the value for t_m_video_type.t_type_info
     *
     * @mbggenerated Fri Dec 29 14:14:40 CST 2017
     */
    public void settTypeInfo(String tTypeInfo) {
        this.tTypeInfo = tTypeInfo;
    }
}