package com.letu.healthplatform.platformmanage.home.model;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_id
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_title
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private String tTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_video_url
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private String tVideoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_video_click
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private Integer tVideoClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_type_id
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private Integer tTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_status
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private Integer tStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_create_time
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private Date tCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_create_by
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private String tCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_modify_time
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private Date tModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_m_video.t_modify_by
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    private String tModifyBy;
    
    /***
     * 类型
     */
    private String tType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_id
     *
     * @return the value of t_m_video.t_id
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_id
     *
     * @param tId the value for t_m_video.t_id
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_title
     *
     * @return the value of t_m_video.t_title
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public String gettTitle() {
        return tTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_title
     *
     * @param tTitle the value for t_m_video.t_title
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settTitle(String tTitle) {
        this.tTitle = tTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_video_url
     *
     * @return the value of t_m_video.t_video_url
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public String gettVideoUrl() {
        return tVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_video_url
     *
     * @param tVideoUrl the value for t_m_video.t_video_url
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settVideoUrl(String tVideoUrl) {
        this.tVideoUrl = tVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_video_click
     *
     * @return the value of t_m_video.t_video_click
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public Integer gettVideoClick() {
        return tVideoClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_video_click
     *
     * @param tVideoClick the value for t_m_video.t_video_click
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settVideoClick(Integer tVideoClick) {
        this.tVideoClick = tVideoClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_type_id
     *
     * @return the value of t_m_video.t_type_id
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public Integer gettTypeId() {
        return tTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_type_id
     *
     * @param tTypeId the value for t_m_video.t_type_id
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settTypeId(Integer tTypeId) {
        this.tTypeId = tTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_status
     *
     * @return the value of t_m_video.t_status
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_status
     *
     * @param tStatus the value for t_m_video.t_status
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_create_time
     *
     * @return the value of t_m_video.t_create_time
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public Date gettCreateTime() {
        return tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_create_time
     *
     * @param tCreateTime the value for t_m_video.t_create_time
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settCreateTime(Date tCreateTime) {
        this.tCreateTime = tCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_create_by
     *
     * @return the value of t_m_video.t_create_by
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public String gettCreateBy() {
        return tCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_create_by
     *
     * @param tCreateBy the value for t_m_video.t_create_by
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settCreateBy(String tCreateBy) {
        this.tCreateBy = tCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_modify_time
     *
     * @return the value of t_m_video.t_modify_time
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public Date gettModifyTime() {
        return tModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_modify_time
     *
     * @param tModifyTime the value for t_m_video.t_modify_time
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settModifyTime(Date tModifyTime) {
        this.tModifyTime = tModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_m_video.t_modify_by
     *
     * @return the value of t_m_video.t_modify_by
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public String gettModifyBy() {
        return tModifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_m_video.t_modify_by
     *
     * @param tModifyBy the value for t_m_video.t_modify_by
     *
     * @mbggenerated Fri Dec 29 15:53:40 CST 2017
     */
    public void settModifyBy(String tModifyBy) {
        this.tModifyBy = tModifyBy;
    }

	public String gettType() {
		return tType;
	}

	public void settType(String tType) {
		this.tType = tType;
	}
    
    
}