package com.letu.healthplatform.platformmanage.user.model;

import java.util.Date;

public class AppLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_id
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_nickname
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private String loginNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_telephone
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private String loginTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_password
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_register_time
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private Date loginRegisterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_last_login_time
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private Date loginLastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_status
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private Integer loginStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_wx_openid
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private String loginWxOpenid;
    
    
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_invite
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private String loginInvite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.login_head_image
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    private String loginHeadImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_id
     *
     * @return the value of t_login.login_id
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_id
     *
     * @param loginId the value for t_login.login_id
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_nickname
     *
     * @return the value of t_login.login_nickname
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getLoginNickname() {
        return loginNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_nickname
     *
     * @param loginNickname the value for t_login.login_nickname
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginNickname(String loginNickname) {
        this.loginNickname = loginNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_telephone
     *
     * @return the value of t_login.login_telephone
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getLoginTelephone() {
        return loginTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_telephone
     *
     * @param loginTelephone the value for t_login.login_telephone
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginTelephone(String loginTelephone) {
        this.loginTelephone = loginTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_password
     *
     * @return the value of t_login.login_password
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_password
     *
     * @param loginPassword the value for t_login.login_password
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_register_time
     *
     * @return the value of t_login.login_register_time
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Date getLoginRegisterTime() {
        return loginRegisterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_register_time
     *
     * @param loginRegisterTime the value for t_login.login_register_time
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginRegisterTime(Date loginRegisterTime) {
        this.loginRegisterTime = loginRegisterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_last_login_time
     *
     * @return the value of t_login.login_last_login_time
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Date getLoginLastLoginTime() {
        return loginLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_last_login_time
     *
     * @param loginLastLoginTime the value for t_login.login_last_login_time
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginLastLoginTime(Date loginLastLoginTime) {
        this.loginLastLoginTime = loginLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_status
     *
     * @return the value of t_login.login_status
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public Integer getLoginStatus() {
        return loginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_status
     *
     * @param loginStatus the value for t_login.login_status
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginStatus(Integer loginStatus) {
        this.loginStatus = loginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_wx_openid
     *
     * @return the value of t_login.login_wx_openid
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getLoginWxOpenid() {
        return loginWxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_wx_openid
     *
     * @param loginWxOpenid the value for t_login.login_wx_openid
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginWxOpenid(String loginWxOpenid) {
        this.loginWxOpenid = loginWxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_invite
     *
     * @return the value of t_login.login_invite
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getLoginInvite() {
        return loginInvite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_invite
     *
     * @param loginInvite the value for t_login.login_invite
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginInvite(String loginInvite) {
        this.loginInvite = loginInvite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.login_head_image
     *
     * @return the value of t_login.login_head_image
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public String getLoginHeadImage() {
        return loginHeadImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.login_head_image
     *
     * @param loginHeadImage the value for t_login.login_head_image
     *
     * @mbggenerated Tue Jan 02 09:54:56 CST 2018
     */
    public void setLoginHeadImage(String loginHeadImage) {
        this.loginHeadImage = loginHeadImage;
    }

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
    
    
}