package com.letu.healthplatform.platformmanage.sys.mapper;

import com.letu.healthplatform.platformmanage.sys.model.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    int deleteByPrimaryKey(Integer userinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    UserInfo selectByPrimaryKey(Integer userinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Thu Nov 30 10:53:38 CST 2017
     */
    int updateByPrimaryKey(UserInfo record);
}