package com.letu.healthplatform.platformmanage.report.mapper;

import java.util.List;

import com.letu.healthplatform.platformmanage.report.model.ReportResult;

public interface ReportResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_result
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    int deleteByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_result
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    int insert(ReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_result
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    int insertSelective(ReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_result
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    ReportResult selectByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_result
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    int updateByPrimaryKeySelective(ReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_result
     *
     * @mbggenerated Wed Mar 28 14:57:27 CST 2018
     */
    int updateByPrimaryKey(ReportResult record);
    
    /***
     * 批量新增数据
     * @param reports
     * @return
     */
    int insertBatch(List<ReportResult> reports);
    /***
     * 删除
     * @param sampleNumber
     * @return
     */
    int deleteByParamSampleNumber(String sampleNumber);
     /****
      * 查询
      * @param sampleNumber
      * @return
      */
    List<ReportResult> selectBySampleNumber(String sampleNumber);
}