package com.letu.healthplatform.platformmanage.report.mapper;

import com.letu.healthplatform.platformmanage.report.model.SaleMail;

public interface SaleMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_mail
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_mail
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    int insert(SaleMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_mail
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    int insertSelective(SaleMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_mail
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    SaleMail selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_mail
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    int updateByPrimaryKeySelective(SaleMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sale_mail
     *
     * @mbggenerated Tue Jan 23 13:51:44 CST 2018
     */
    int updateByPrimaryKey(SaleMail record);
}